name: Cu Reabtha Border Collies
favicon: null
layout_spectrum: 0.49284
typography_spectrum: 0.24358
title: Cu Reabtha Border Collies - An AKC Breeder of Merit
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#fbfaf8'
    - '#586631'
    - '#c1bcb8'
    - '#a09989'
  brandStrength: 0.5663826386444271
  lightness: 0.5
  saturation: 0.4107021288946271
  rhythmicContrast: 0.5
purpose: []
